=== clausmith/onecodex/tests/api_data/schema_analyses.json
{"$schema": "http://json-schema.org/draft-04/hyper-schema#", "type": "object", "properties": {"complete": {"type": ["boolean", "null"]}, "$uri": {"pattern": "^\\/api\\/v1\\/analyses\\/[^/]+$", "readOnly": true, "type": "string"}, "created_at": {"readOnly": true, "type": "string", "format": "date-time"}, "success": {"type": ["boolean", "null"]}, "sample": {"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}}, "job": {"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}}, "analysis_type": {"type": ["string", "null"], "maxLength": 50}, "error_msg": {"type": ["string", "null"], "maxLength": 255}}, "links": [{"href": "/api/v1/analyses/schema", "method": "GET", "rel": "describedBy"}, {"targetSchema": {"items": {"$ref": "#"}, "type": "array"}, "href": "/api/v1/analyses", "method": "GET", "rel": "instances", "schema": {"additionalProperties": true, "type": "object", "properties": {"sort": {"additionalProperties": false, "type": "object", "properties": {"complete": {"type": "boolean", "description": "Sort by complete in descending order if 'true', ascending order if 'false'."}, "$uri": {"type": "boolean", "description": "Sort by $uri in descending order if 'true', ascending order if 'false'."}, "created_at": {"type": "boolean", "description": "Sort by created_at in descending order if 'true', ascending order if 'false'."}, "success": {"type": "boolean", "description": "Sort by success in descending order if 'true', ascending order if 'false'."}, "sample": {"type": "boolean", "description": "Sort by sample in descending order if 'true', ascending order if 'false'."}, "job": {"type": "boolean", "description": "Sort by job in descending order if 'true', ascending order if 'false'."}, "analysis_type": {"type": "boolean", "description": "Sort by analysis_type in descending order if 'true', ascending order if 'false'."}, "error_msg": {"type": "boolean", "description": "Sort by error_msg in descending order if 'true', ascending order if 'false'."}}}, "per_page": {"default": 20, "minimum": 1, "type": "integer", "maximum": 1000}, "where": {"additionalProperties": false, "type": "object", "properties": {"complete": {"anyOf": [{"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"type": ["boolean", "null"]}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"type": ["boolean", "null"]}}}, {"type": ["boolean", "null"]}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"type": ["boolean", "null"]}, "uniqueItems": true, "type": "array"}}}]}, "$uri": {"anyOf": [{"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"pattern": "^\\/api\\/v1\\/analyses\\/[^/]+$", "type": "string"}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"pattern": "^\\/api\\/v1\\/analyses\\/[^/]+$", "type": "string"}}}, {"pattern": "^\\/api\\/v1\\/analyses\\/[^/]+$", "type": "string"}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"pattern": "^\\/api\\/v1\\/analyses\\/[^/]+$", "type": "string"}, "uniqueItems": true, "type": "array"}}}]}, "created_at": {"anyOf": [{"additionalProperties": false, "required": ["$gt"], "type": "object", "properties": {"$gt": {"type": "string", "format": "date-time"}}}, {"type": "string", "format": "date-time"}, {"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"type": "string", "format": "date-time"}}}, {"additionalProperties": false, "required": ["$lt"], "type": "object", "properties": {"$lt": {"type": "string", "format": "date-time"}}}, {"additionalProperties": false, "required": ["$lte"], "type": "object", "properties": {"$lte": {"type": "string", "format": "date-time"}}}, {"additionalProperties": false, "required": ["$between"], "type": "object", "properties": {"$between": {"minItems": 2, "items": {"type": "string", "format": "date-time"}, "type": "array", "maxItems": 2}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"type": "string", "format": "date-time"}}}, {"additionalProperties": false, "required": ["$gte"], "type": "object", "properties": {"$gte": {"type": "string", "format": "date-time"}}}]}, "success": {"anyOf": [{"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"type": ["boolean", "null"]}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"type": ["boolean", "null"]}}}, {"type": ["boolean", "null"]}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"type": ["boolean", "null"]}, "uniqueItems": true, "type": "array"}}}]}, "sample": {"anyOf": [{"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"anyOf": [{"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}}, {"type": ["string", "null"], "maxLength": 16}]}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"anyOf": [{"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}}, {"type": ["string", "null"], "maxLength": 16}]}}}, {"anyOf": [{"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}}, {"type": ["string", "null"], "maxLength": 16}]}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"anyOf": [{"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}}, {"type": ["string", "null"], "maxLength": 16}]}, "uniqueItems": true, "type": "array"}}}]}, "job": {"anyOf": [{"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"anyOf": [{"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}}, {"type": ["string", "null"], "maxLength": 16}]}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"anyOf": [{"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}}, {"type": ["string", "null"], "maxLength": 16}]}}}, {"anyOf": [{"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}}, {"type": ["string", "null"], "maxLength": 16}]}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"anyOf": [{"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}}, {"type": ["string", "null"], "maxLength": 16}]}, "uniqueItems": true, "type": "array"}}}]}, "analysis_type": {"anyOf": [{"additionalProperties": false, "required": ["$startswith"], "type": "object", "properties": {"$startswith": {"minLength": 1, "type": "string"}}}, {"type": ["string", "null"], "maxLength": 50}, {"additionalProperties": false, "required": ["$contains"], "type": "object", "properties": {"$contains": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"type": ["string", "null"], "maxLength": 50}}}, {"additionalProperties": false, "required": ["$iendswith"], "type": "object", "properties": {"$iendswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$icontains"], "type": "object", "properties": {"$icontains": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$endswith"], "type": "object", "properties": {"$endswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$istartswith"], "type": "object", "properties": {"$istartswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"type": ["string", "null"], "maxLength": 50}, "uniqueItems": true, "type": "array"}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"type": ["string", "null"], "maxLength": 50}}}]}, "error_msg": {"anyOf": [{"additionalProperties": false, "required": ["$startswith"], "type": "object", "properties": {"$startswith": {"minLength": 1, "type": "string"}}}, {"type": ["string", "null"], "maxLength": 255}, {"additionalProperties": false, "required": ["$contains"], "type": "object", "properties": {"$contains": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"type": ["string", "null"], "maxLength": 255}}}, {"additionalProperties": false, "required": ["$iendswith"], "type": "object", "properties": {"$iendswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$icontains"], "type": "object", "properties": {"$icontains": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$endswith"], "type": "object", "properties": {"$endswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$istartswith"], "type": "object", "properties": {"$istartswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"type": ["string", "null"], "maxLength": 255}, "uniqueItems": true, "type": "array"}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"type": ["string", "null"], "maxLength": 255}}}]}}}, "page": {"default": 1, "minimum": 1, "type": "integer"}}}}, {"targetSchema": {"$ref": "#"}, "href": "/api/v1/analyses/{id}", "method": "GET", "rel": "self"}]}

=== clausmith/onecodex/tests/api_data/analyses.json
[{"complete": true, "$uri": "/api/v1/analyses/f9e4a5506b154953", "created_at": "2015-09-25T17:44:08.343070-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/688337f1e5bf4c65"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/2d223f1a7e3a4d83", "created_at": "2015-09-25T18:13:39.274875-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/002f55a11aae4b8f"}, "job": {"$ref": "/api/v1/jobs/47c4fe23588640a9"}, "analysis_type": "typing", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/3e03c1d8ac6244a1", "created_at": "2016-04-26T13:25:09.804413-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/c8e7d2ca603b48d4"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/fc14fdb8ba8b4bca", "created_at": "2015-09-25T17:42:53.886758-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/8a744cd3d04a4974"}, "job": {"$ref": "/api/v1/jobs/1ede4125214542e0"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/440049979dc04a6a", "created_at": "2015-09-25T17:31:56.925474-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/cfcb4967fb464beb"}, "job": {"$ref": "/api/v1/jobs/1ede4125214542e0"}, "analysis_type": "classification", "error_msg": ""}, {"complete": false, "$uri": "/api/v1/analyses/01023a286e8c4ed0", "created_at": "2016-04-26T13:25:24.688662-07:00", "success": false, "sample": {"$ref": "/api/v1/samples/8f85efa7d7fe4097"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/b899ea3192a84da2", "created_at": "2016-04-26T13:25:48.232483-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/a9c338af519f429e"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/0ee89daf510b4a65", "created_at": "2015-09-25T17:45:06.156385-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/1d8a204f05b14918"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/b00584d5b42b4bd9", "created_at": "2015-09-25T18:34:55.369097-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/0eca33117b3347ac"}, "job": {"$ref": "/api/v1/jobs/47c4fe23588640a9"}, "analysis_type": "typing", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/25de3241e33e415b", "created_at": "2015-09-25T17:31:56.750082-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/c83400116243403c"}, "job": {"$ref": "/api/v1/jobs/1ede4125214542e0"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/1e7faa4de5a945ee", "created_at": "2015-09-25T17:33:18.735084-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/19ce44ee6f3943bf"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/1c8f45b43ab84a48", "created_at": "2015-09-25T18:00:45.338150-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/4bdfac4313aa4209"}, "job": {"$ref": "/api/v1/jobs/47c4fe23588640a9"}, "analysis_type": "typing", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/a7fbafe3c73645cd", "created_at": "2016-04-26T13:25:26.602755-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/429b25f816cf41bc"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/937677e2f16f4682", "created_at": "2016-04-26T13:25:17.797473-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/54d17ca5b2b1422e"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/bc94b2b45ca341be", "created_at": "2015-09-25T17:43:52.163866-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/15055801e0e34633"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/a7bfb446d6944519", "created_at": "2015-09-25T17:41:33.115194-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/5adfccc1093e4555"}, "job": {"$ref": "/api/v1/jobs/1ede4125214542e0"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/90fac9b68e2548a0", "created_at": "2016-04-26T13:25:26.746907-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/712709033c5d4822"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/c29bedbf61c24408", "created_at": "2015-09-25T18:07:37.571605-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/8b4bc4d8d3544d36"}, "job": {"$ref": "/api/v1/jobs/47c4fe23588640a9"}, "analysis_type": "typing", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/965185f01841480c", "created_at": "2015-09-25T17:40:37.736744-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/e36900f6ad884d1a"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/2df943a7ebfa4fed", "created_at": "2015-09-25T17:39:31.081505-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/c0ed3d99241b4c1e"}, "job": {"$ref": "/api/v1/jobs/1ede4125214542e0"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/6502c04516cd4869", "created_at": "2015-09-25T17:35:36.422434-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/2344132f75b74f33"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/20d07f451d2148a0", "created_at": "2016-04-26T13:25:52.331534-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/022b29421b794ff1"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/a7b178055b884761", "created_at": "2015-09-25T18:13:38.465325-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/4385779ab7d24872"}, "job": {"$ref": "/api/v1/jobs/47c4fe23588640a9"}, "analysis_type": "typing", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/3ae055db07934bdc", "created_at": "2015-09-25T17:39:56.863607-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/712709033c5d4822"}, "job": {"$ref": "/api/v1/jobs/1ede4125214542e0"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/593601a797914cbf", "created_at": "2015-09-25T17:27:30.622286-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/7428cca4a3a04a8e"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/69a99eaa91bd4744", "created_at": "2016-04-26T13:25:27.384334-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/03d55899b4d644df"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/8db2b7d308184808", "created_at": "2015-09-25T17:35:05.349327-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/8b4bc4d8d3544d36"}, "job": {"$ref": "/api/v1/jobs/1ede4125214542e0"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/9528bd3597214443", "created_at": "2015-09-25T17:43:54.723075-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/1a031306b40d4d61"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/98523a2f46bc4b1b", "created_at": "2015-09-25T17:38:58.221193-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/cb88d2500b754571"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/1a19739f12034508", "created_at": "2016-04-26T13:25:56.878065-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/9e1052fc334340ee"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/81346a1996404f2a", "created_at": "2015-09-25T17:31:37.296320-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/4bdfac4313aa4209"}, "job": {"$ref": "/api/v1/jobs/e4b1ab37ff554c53"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/8adb298751584d99", "created_at": "2016-04-26T13:25:17.183756-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/8a744cd3d04a4974"}, "job": {"$ref": "/api/v1/jobs/c3caae64b63b4f07"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/c23269af3b064737", "created_at": "2015-09-25T17:40:15.978794-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/8f85efa7d7fe4097"}, "job": {"$ref": "/api/v1/jobs/1ede4125214542e0"}, "analysis_type": "classification", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/5842defe365c43d9", "created_at": "2015-09-25T18:35:12.986680-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/d28cb06eff204a5c"}, "job": {"$ref": "/api/v1/jobs/47c4fe23588640a9"}, "analysis_type": "typing", "error_msg": ""}, {"complete": true, "$uri": "/api/v1/analyses/a06646b2185a489b", "created_at": "2015-09-25T18:13:10.876750-07:00", "success": true, "sample": {"$ref": "/api/v1/samples/0ca0f71a1b534b03"}
