=== clausmith/onecodex/tests/api_data/schema_jobs.json
{"$schema": "http://json-schema.org/draft-04/hyper-schema#", "type": "object", "properties": {"name": {"type": ["string", "null"], "maxLength": 60}, "$uri": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "readOnly": true, "type": "string"}, "created_at": {"readOnly": true, "type": "string", "format": "date-time"}, "current": {"default": true, "type": ["boolean", "null"]}, "analysis_type": {"type": ["string", "null"], "maxLength": 50}, "public": {"default": false, "type": ["boolean", "null"]}}, "links": [{"href": "/api/v1/jobs/schema", "method": "GET", "rel": "describedBy"}, {"targetSchema": {"items": {"$ref": "#"}, "type": "array"}, "href": "/api/v1/jobs", "method": "GET", "rel": "instances", "schema": {"additionalProperties": true, "type": "object", "properties": {"sort": {"additionalProperties": false, "type": "object", "properties": {"name": {"type": "boolean", "description": "Sort by name in descending order if 'true', ascending order if 'false'."}, "$uri": {"type": "boolean", "description": "Sort by $uri in descending order if 'true', ascending order if 'false'."}, "created_at": {"type": "boolean", "description": "Sort by created_at in descending order if 'true', ascending order if 'false'."}, "current": {"type": "boolean", "description": "Sort by current in descending order if 'true', ascending order if 'false'."}, "analysis_type": {"type": "boolean", "description": "Sort by analysis_type in descending order if 'true', ascending order if 'false'."}, "public": {"type": "boolean", "description": "Sort by public in descending order if 'true', ascending order if 'false'."}}}, "per_page": {"default": 20, "minimum": 1, "type": "integer", "maximum": 1000}, "where": {"additionalProperties": false, "type": "object", "properties": {"name": {"anyOf": [{"additionalProperties": false, "required": ["$startswith"], "type": "object", "properties": {"$startswith": {"minLength": 1, "type": "string"}}}, {"type": ["string", "null"], "maxLength": 60}, {"additionalProperties": false, "required": ["$contains"], "type": "object", "properties": {"$contains": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"type": ["string", "null"], "maxLength": 60}}}, {"additionalProperties": false, "required": ["$iendswith"], "type": "object", "properties": {"$iendswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$icontains"], "type": "object", "properties": {"$icontains": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$endswith"], "type": "object", "properties": {"$endswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$istartswith"], "type": "object", "properties": {"$istartswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"type": ["string", "null"], "maxLength": 60}, "uniqueItems": true, "type": "array"}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"type": ["string", "null"], "maxLength": 60}}}]}, "$uri": {"anyOf": [{"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}}, {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}, "uniqueItems": true, "type": "array"}}}]}, "created_at": {"anyOf": [{"additionalProperties": false, "required": ["$gt"], "type": "object", "properties": {"$gt": {"type": "string", "format": "date-time"}}}, {"type": "string", "format": "date-time"}, {"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"type": "string", "format": "date-time"}}}, {"additionalProperties": false, "required": ["$lt"], "type": "object", "properties": {"$lt": {"type": "string", "format": "date-time"}}}, {"additionalProperties": false, "required": ["$lte"], "type": "object", "properties": {"$lte": {"type": "string", "format": "date-time"}}}, {"additionalProperties": false, "required": ["$between"], "type": "object", "properties": {"$between": {"minItems": 2, "items": {"type": "string", "format": "date-time"}, "type": "array", "maxItems": 2}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"type": "string", "format": "date-time"}}}, {"additionalProperties": false, "required": ["$gte"], "type": "object", "properties": {"$gte": {"type": "string", "format": "date-time"}}}]}, "current": {"anyOf": [{"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"default": true, "type": ["boolean", "null"]}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"default": true, "type": ["boolean", "null"]}}}, {"default": true, "type": ["boolean", "null"]}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"default": true, "type": ["boolean", "null"]}, "uniqueItems": true, "type": "array"}}}]}, "analysis_type": {"anyOf": [{"additionalProperties": false, "required": ["$startswith"], "type": "object", "properties": {"$startswith": {"minLength": 1, "type": "string"}}}, {"type": ["string", "null"], "maxLength": 50}, {"additionalProperties": false, "required": ["$contains"], "type": "object", "properties": {"$contains": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"type": ["string", "null"], "maxLength": 50}}}, {"additionalProperties": false, "required": ["$iendswith"], "type": "object", "properties": {"$iendswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$icontains"], "type": "object", "properties": {"$icontains": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$endswith"], "type": "object", "properties": {"$endswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$istartswith"], "type": "object", "properties": {"$istartswith": {"minLength": 1, "type": "string"}}}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"type": ["string", "null"], "maxLength": 50}, "uniqueItems": true, "type": "array"}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"type": ["string", "null"], "maxLength": 50}}}]}, "public": {"anyOf": [{"additionalProperties": false, "required": ["$ne"], "type": "object", "properties": {"$ne": {"default": false, "type": ["boolean", "null"]}}}, {"additionalProperties": false, "required": ["$eq"], "type": "object", "properties": {"$eq": {"default": false, "type": ["boolean", "null"]}}}, {"default": false, "type": ["boolean", "null"]}, {"additionalProperties": false, "required": ["$in"], "type": "object", "properties": {"$in": {"minItems": 0, "items": {"default": false, "type": ["boolean", "null"]}, "uniqueItems": true, "type": "array"}}}]}}}, "page": {"default": 1, "minimum": 1, "type": "integer"}}}}, {"targetSchema": {"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/analyses\\/[^/]+$", "type": "string"}}}, "href": "/api/v1/jobs/{id}/run", "method": "POST", "rel": "run", "schema": {"additionalProperties": false, "required": ["sample", "job_args"], "type": "object", "properties": {"sample": {"anyOf": [{"additionalProperties": false, "type": "object", "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}}, {"type": ["string", "null"], "maxLength": 16}]}, "job_args": {"additionalProperties": {"type": ["null", "string", "number", "boolean", "object", "array"]}, "type": "object"}}}}, {"targetSchema": {"$ref": "#"}, "href": "/api/v1/jobs/{id}", "method": "GET", "rel": "self"}]}

=== clausmith/onecodex/tests/api_data/jobs.json
[{"name": "Alignment Run", "$uri": "/api/v1/jobs/9359554ff4f34137", "created_at": "2015-09-14T13:20:15.528558-07:00", "current": false, "analysis_type": "alignment", "public": false}, {"name": "Alignment", "$uri": "/api/v1/jobs/fd5f5264781d477e", "created_at": "2016-07-12T16:42:46.234631-07:00", "current": true, "analysis_type": "alignment", "public": true}, {"name": "RefSeq Complete Genomes", "$uri": "/api/v1/jobs/52c73e0c9a4d4b3f", "created_at": "2015-11-01T16:28:03.974596-08:00", "current": true, "analysis_type": "classification", "public": true}, {"name": "ARD Panel v1", "$uri": "/api/v1/jobs/c4f763556452402c", "created_at": "2015-09-11T17:43:58.818569-07:00", "current": false, "analysis_type": "markerpanel", "public": false}, {"name": "One Codex (NNLS) (latest)", "$uri": "/api/v1/jobs/c3caae64b63b4f07", "created_at": "2016-04-07T14:47:36.054255-07:00", "current": true, "analysis_type": "classification", "public": false}, {"name": "One Codex 38K Database", "$uri": "/api/v1/jobs/1ede4125214542e0", "created_at": "2015-08-31T16:38:25.833478-07:00", "current": false, "analysis_type": "classification", "public": false}, {"name": "One Codex Database w/NNLS", "$uri": "/api/v1/jobs/b18ea5e828224e3c", "created_at": "2016-02-08T13:56:55.156056-08:00", "current": true, "analysis_type": "classification", "public": true}, {"name": "RefSeq Complete Genomes", "$uri": "/api/v1/jobs/e4b1ab37ff554c53", "created_at": "2015-09-01T10:11:15.493388-07:00", "current": true, "analysis_type": "classification", "public": true}, {"name": "Targeted Loci Database", "$uri": "/api/v1/jobs/7076363bfd204971", "created_at": "2016-05-01T17:28:52.104426-07:00", "current": true, "analysis_type": "classification", "public": true}, {"name": "One Codex S. enterica Typing", "$uri": "/api/v1/jobs/47c4fe23588640a9", "created_at": "2015-04-28T17:45:49-07:00", "current": false, "analysis_type": "typing", "public": false}, {"name": "One Codex Database w/NNLS", "$uri": "/api/v1/jobs/0d558feada6f47ac", "created_at": "2016-02-09T08:38:49.504357-08:00", "current": true, "analysis_type": "classification", "public": true}, {"name": "One Codex Database", "$uri": "/api/v1/jobs/d512cb556241440f", "created_at": "2015-11-01T16:27:19.140577-08:00", "current": true, "analysis_type": "classification", "public": true}]
